---
- name: configure slave serverconf db
  include: serverconf_slave_db.yml

- name: do initial configuration sync
  become_user: xroad
  become: yes
  command: rsync -e "ssh -o StrictHostKeyChecking=no" -aqz --delete-delay --exclude "/db.properties" --exclude "/conf.d/node.ini" --exclude "*.tmp" --exclude "/postgresql" --exclude "/nginx" "{{ xroad_slave_ssh_user }}@{{ master_host }}":/etc/xroad/ /etc/xroad/

- name: install sync cron job
  template: 
      src: "xroad_slave_sync.j2" 
      dest: "/etc/cron.d/xroad-slave-sync"

- name: rotate sync logs
  copy: 
      src: "xroad-slave-sync.logrotate" 
      dest: "/etc/logrotate.d/xroad-slave-sync"

- name: enable slave role for node
  ini_file: dest=/etc/xroad/conf.d/node.ini
            section=node
            option=type
            value=slave
            create=true
            mode=0640
            owner=root
            group=xroad

- name: start services
  service:
      name: "{{ item }}"
      state: started
  with_items:
      - xroad-proxy
      - xroad-confclient
      - xroad-signer
      - xroad-jetty

