test:
  adapter: jdbcsqlite3
  encoding: utf8
  database: build/centerservice_test.sqlite3

development:
  adapter: postgresql
  encoding: utf8
  username: centerui
  password: centerui # from psql setup, see Postgresql
  database: centerui_development

# Use the following environment for running center-service instances on
# a BDR cluster.
# Start rails with a command similar to:
# jruby -S rails s -p 3345 -P tmp/server_3345.pid -e devel_ha
devel_ha:
  adapter: postgresql
  encoding: utf8
  username: iks2
  database: centerui_test_pg
  port: 5599 # Make sure a clustered database is running on this port.
