development:
  adapter: postgresql
  encoding: utf8
  username: centerui
  password: centerui # from psql setup, see Postgresql
  database: centerui_development

  # XXX: Comment following lines in and use proper port for quick
  # access to iks2-central or some other machine other than Your own

  # port: 15432 # Assumes that port with this number is forwarded
  # database: centerui_production

test:
  adapter: jdbcsqlite3
  encoding: utf8
  database: build/centerui_test.sqlite3

test_pg:
  adapter: postgresql
  encoding: utf8
  username: centerui_test_pg
  password: centerui
  database: centerui_test_pg
