# This file contains the full list of privileges used in center-UI authorization.
# Each privilege is mapped to a list of roles that it belongs to.

# roles:
#   - sdsb-security-officer
#   - sdsb-registration-officer
#   - sdsb-system-administrator

- view_members: [sdsb-registration-officer, sdsb-system-administrator]
-   add_new_member: [sdsb-registration-officer]
- view_member_details: [sdsb-registration-officer]
-   edit_member_name_and_admin_contact: [sdsb-registration-officer]
-   add_security_server_reg_request: [sdsb-registration-officer]
-   member_to_global_group_add_remove: [sdsb-registration-officer]
-   remove_member_subsystem: [sdsb-registration-officer]
-   add_security_server_client_reg_request: [sdsb-registration-officer]
-   stop_or_continue_security_server_client_data_exchange: [sdsb-registration-officer]
-   remove_member_from_security_server_clients: [sdsb-registration-officer]
-   delete_member: [sdsb-registration-officer]
- view_security_servers: [sdsb-registration-officer, sdsb-system-administrator]
- view_security_server_details: [sdsb-registration-officer]
-   edit_security_server_address: [sdsb-registration-officer]
-   edit_security_server_security_category: [sdsb-registration-officer]
-   add_security_server_auth_cert_reg_request: [sdsb-registration-officer]
-   delete_security_server_auth_cert: [sdsb-registration-officer]
-   delete_security_server: [sdsb-registration-officer]
- view_global_groups: [sdsb-registration-officer, sdsb-system-administrator]
-   add_global_group: [sdsb-registration-officer]
-   view_group_details: [sdsb-registration-officer]
-     edit_group_description: [sdsb-registration-officer]
-     add_and_remove_group_members: [sdsb-registration-officer]
-     delete_group: [sdsb-registration-officer]
- view_central_services: [sdsb-registration-officer, sdsb-system-administrator]
-   view_central_service_details: [sdsb-system-administrator]
-   add_central_service: [sdsb-system-administrator]
-   edit_implementing_service: [sdsb-system-administrator]
-   remove_central_service: [sdsb-system-administrator]
- view_approved_cas: [sdsb-registration-officer, sdsb-system-administrator]
-   view_approved_ca_details: [sdsb-system-administrator]
-   add_approved_ca: [sdsb-system-administrator]
-   edit_approved_ca: [sdsb-system-administrator]
-   delete_approved_ca: [sdsb-system-administrator]
- view_approved_tsps: [sdsb-registration-officer, sdsb-system-administrator]
-   view_approved_tsp_details: [sdsb-system-administrator]
-   add_approved_tsp: [sdsb-system-administrator]
-   edit_approved_tsp: [sdsb-system-administrator]
-   delete_approved_tsp: [sdsb-system-administrator]
- view_management_requests: [sdsb-registration-officer]
-   view_management_request_details: [sdsb-registration-officer]
-     confirm_auth_cert_reg_request: [sdsb-registration-officer]
-     decline_auth_cert_reg_request: [sdsb-registration-officer]
-     confirm_security_server_client_reg_request: [sdsb-registration-officer]
-     decline_security_server_client_reg_request: [sdsb-registration-officer]
- view_member_classes: [sdsb-registration-officer, sdsb-system-administrator]
-   add_member_class: [sdsb-system-administrator]
-   edit_member_class: [sdsb-system-administrator]
-   delete_member_class: [sdsb-system-administrator]
- view_security_categories: [sdsb-registration-officer, sdsb-system-administrator]
-   add_security_category: [sdsb-system-administrator]
-   edit_security_category: [sdsb-system-administrator]
-   delete_security_category: [sdsb-system-administrator]
- view_configuration: [sdsb-registration-officer, sdsb-system-administrator]
-   edit_management_services_address: [sdsb-system-administrator]
-   edit_signing_key_and_cert: [sdsb-security-officer]
- view_distributed_files: [sdsb-registration-officer, sdsb-system-administrator]
-   upload_identifier_mapping: [sdsb-registration-officer]
- execute_v5_import: [sdsb-registration-officer]
- backup_configuration: [sdsb-system-administrator]
- restore_configuration: [sdsb-system-administrator]
- enter_signing_token_pin: [sdsb-system-administrator]
