# This file contains the full list of privileges used in center-UI authorization.
# Each privilege is mapped to a list of roles that it belongs to.

# roles:
#   - xroad-security-officer
#   - xroad-registration-officer
#   - xroad-system-administrator

- init_config: [xroad-system-administrator, xroad-security-officer]
- search_members: [xroad-security-officer, xroad-registration-officer]
- view_members: [xroad-registration-officer, xroad-system-administrator]
-   add_new_member: [xroad-registration-officer]
- view_member_details: [xroad-registration-officer]
-   edit_member_name_and_admin_contact: [xroad-registration-officer]
-   add_security_server_reg_request: [xroad-registration-officer]
-   member_to_global_group_add_remove: [xroad-registration-officer]
-   remove_member_subsystem: [xroad-registration-officer]
-   add_security_server_client_reg_request: [xroad-registration-officer]
-   stop_or_continue_security_server_client_data_exchange: [xroad-registration-officer]
-   remove_member_from_security_server_clients: [xroad-registration-officer]
-   delete_member: [xroad-registration-officer]
- view_security_servers: [xroad-registration-officer, xroad-system-administrator]
- view_security_server_details: [xroad-registration-officer]
-   edit_security_server_address: [xroad-registration-officer]
-   edit_security_server_security_category: [xroad-registration-officer]
-   add_security_server_auth_cert_reg_request: [xroad-registration-officer]
-   delete_security_server_auth_cert: [xroad-registration-officer]
-   delete_security_server: [xroad-registration-officer]
- view_global_groups: [xroad-registration-officer, xroad-system-administrator]
-   add_global_group: [xroad-registration-officer]
-   view_group_details: [xroad-registration-officer]
-     edit_group_description: [xroad-registration-officer]
-     add_and_remove_group_members: [xroad-registration-officer]
-     delete_group: [xroad-registration-officer]
- view_central_services: [xroad-registration-officer, xroad-system-administrator]
-   view_central_service_details: [xroad-system-administrator]
-   add_central_service: [xroad-system-administrator]
-   edit_implementing_service: [xroad-system-administrator]
-   remove_central_service: [xroad-system-administrator]
- view_approved_cas: [xroad-registration-officer, xroad-system-administrator]
-   view_approved_ca_details: [xroad-system-administrator]
-   add_approved_ca: [xroad-system-administrator]
-   edit_approved_ca: [xroad-system-administrator]
-   delete_approved_ca: [xroad-system-administrator]
- view_approved_tsas: [xroad-registration-officer, xroad-system-administrator]
-   view_approved_tsa_details: [xroad-system-administrator]
-   add_approved_tsa: [xroad-system-administrator]
-   edit_approved_tsa: [xroad-system-administrator]
-   delete_approved_tsa: [xroad-system-administrator]
- view_management_requests: [xroad-registration-officer]
-   view_management_request_details: [xroad-registration-officer]
-     confirm_auth_cert_reg_request: [xroad-registration-officer]
-     decline_auth_cert_reg_request: [xroad-registration-officer]
-     confirm_security_server_client_reg_request: [xroad-registration-officer]
-     decline_security_server_client_reg_request: [xroad-registration-officer]
- view_member_classes: [xroad-registration-officer, xroad-system-administrator]
-   add_member_class: [xroad-system-administrator]
-   edit_member_class: [xroad-system-administrator]
-   delete_member_class: [xroad-system-administrator]
- view_security_categories: [xroad-registration-officer, xroad-system-administrator]
-   add_security_category: [xroad-system-administrator]
-   edit_security_category: [xroad-system-administrator]
-   delete_security_category: [xroad-system-administrator]
- view_configuration: [xroad-registration-officer, xroad-system-administrator]
-   edit_management_services_address: [xroad-system-administrator]
-   edit_signing_key_and_cert: [xroad-security-officer]
- view_configuration_management: [xroad-system-administrator, xroad-security-officer, xroad-registration-officer]
-   view_trusted_anchors: [xroad-system-administrator, xroad-security-officer]
-   upload_trusted_anchor: [xroad-security-officer]
-   delete_trusted_anchor: [xroad-security-officer]
-   download_trusted_anchor: [xroad-system-administrator, xroad-security-officer]
-   view_internal_configuration_source: [xroad-system-administrator, xroad-security-officer, xroad-registration-officer]
-   view_external_configuration_source: [xroad-system-administrator, xroad-security-officer]
-     generate_source_anchor: [xroad-security-officer]
-     download_source_anchor: [xroad-security-officer]
-     upload_configuration_part: [xroad-security-officer, xroad-registration-officer]
-     download_configuration_part: [xroad-system-administrator, xroad-security-officer]
-     activate_token: [xroad-system-administrator, xroad-security-officer]
-     deactivate_token: [xroad-system-administrator, xroad-security-officer]
-     generate_signing_key: [xroad-security-officer]
-     activate_signing_key: [xroad-security-officer]
-     delete_signing_key: [xroad-security-officer]
- view_system_settings: [xroad-security-officer]
- execute_v5_import: [xroad-registration-officer]
- backup_configuration: [xroad-system-administrator]
- restore_configuration: [xroad-system-administrator]
