---
- name: "update apt cache"
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: "install configuration proxy"
  apt:
    name: "{{ item }}"
    state: present
  when: ansible_os_family == "Debian"
  with_items:
    - xroad-confproxy

