---
- name: Compile xroad modules {{selected_modules}}
  command: ../xtee6/compile_module.sh {{modules[item].dir}} {{modules[item].build}}
  args:
    chdir: ../xtee6
  with_items: "{{selected_modules.split(',')}}"
