# By default, the central server uses this environment if it is run from the source tree.
development:
  adapter: postgresql
  encoding: utf8
  username: centerui
  password: centerui
  database: centerui_development

  # XXX: Comment following lines in and use proper port for quick
  # access to iks2-central or some other machine other than Your own
  # port: 15432 # Assumes that port with this number is forwarded
  # database: centerui_production

# Unit tests are run using SQLite.
test:
  adapter: jdbcsqlite3
  encoding: utf8
  database: build/centerui_test.sqlite3

# Use the following environment for running automated tests against a
# single HA node that has been created with the clusterhelper script.
test_pg:
  adapter: postgresql
  database: centerui_production
  encoding: utf8
  username: centerui
  password: centerui
  host: localhost
  port: 5432

# Use the following environment for running two or more central server instances on
# a BDR cluster that has been created with the clusterhelper script.
# Note that the name of the environment must start with 'devel' for testing
# the UI without authentication.
# If the servers share the host, edit the port numbers accordingly.
# Start rails with a command similar to:
# jruby -S rails s -p 3344 -P tmp/server_3344.pid -e devel_ha
devel_ha:
  adapter: postgresql
  database: centerui_production
  encoding: utf8
  username: centerui
  password: centerui
  host: localhost
  port: 5432
