# This file contains the full list of privileges used in UI authorization.
# Each privilege is mapped to a list of roles that it belongs to.

# roles:
#   - sdsb-security-officer
#   - sdsb-registration-officer
#   - sdsb-service-administrator
#   - sdsb-system-administrator

- init_config: [sdsb-system-administrator]
- view_clients: [sdsb-security-officer, sdsb-registration-officer, sdsb-service-administrator]
-   add_client: [sdsb-registration-officer]
-   send_client_reg_req: [sdsb-registration-officer]
-   view_client_details: [sdsb-registration-officer, sdsb-service-administrator]
-     send_client_del_req: [sdsb-registration-officer]
-     delete_client: [sdsb-registration-officer]
-   view_client_local_groups: [sdsb-service-administrator]
-     add_local_group: [sdsb-service-administrator]
-     edit_local_group_desc: [sdsb-service-administrator]
-     edit_local_group_members: [sdsb-service-administrator]
-     delete_local_group: [sdsb-service-administrator]
-   view_client_services: [sdsb-service-administrator]
-     add_wsdl: [sdsb-service-administrator]
-     enable_disable_wsdl: [sdsb-service-administrator]
-     refresh_wsdl: [sdsb-service-administrator]
-     delete_wsdl_missing_services: [sdsb-service-administrator]
-     delete_wsdl: [sdsb-service-administrator]
-     mark_wsdl_publishable: [sdsb-service-administrator]
-     publish_wsdls: [sdsb-service-administrator]
-     edit_service_params: [sdsb-service-administrator]
-     view_service_acl: [sdsb-service-administrator]
-     edit_service_acl: [sdsb-service-administrator]
-     import_export_service_acl: [sdsb-service-administrator]
-     export_client_services_acl: [sdsb-service-administrator]
-   view_client_acl_subjects: [sdsb-service-administrator]
-     view_acl_subject_open_services: [sdsb-service-administrator]
-       edit_acl_subject_open_services: [sdsb-service-administrator]
-   view_client_internal_certs: [sdsb-service-administrator, sdsb-registration-officer]
-     view_client_internal_cert_details: [sdsb-service-administrator, sdsb-registration-officer]
-     add_client_internal_cert: [sdsb-service-administrator, sdsb-registration-officer]
-     delete_client_internal_cert: [sdsb-service-administrator, sdsb-registration-officer]
-     view_client_internal_connection_type: [sdsb-service-administrator, sdsb-registration-officer]
-     edit_client_internal_connection_type: [sdsb-service-administrator, sdsb-registration-officer]
-     view_proxy_internal_cert: [sdsb-service-administrator, sdsb-registration-officer]
-     export_proxy_internal_cert: [sdsb-service-administrator, sdsb-registration-officer]
- view_async_reqs: [sdsb-system-administrator]
-   view_async_req_last_send_result: [sdsb-system-administrator]
-   reset_async_req_send_count: [sdsb-system-administrator]
-   remove_restore_async_req: [sdsb-system-administrator]
- view_async_reqs_log: [sdsb-system-administrator]
- view_keys: [sdsb-security-officer, sdsb-registration-officer, sdsb-system-administrator]
-   login_logout_tokens: [sdsb-security-officer, sdsb-system-administrator]
-   generate_key: [sdsb-security-officer, sdsb-registration-officer]
-   delete_key: [sdsb-security-officer, sdsb-registration-officer]
-   generate_auth_cert_req: [sdsb-security-officer]
-   generate_sign_cert_req: [sdsb-security-officer, sdsb-registration-officer]
-   import_auth_cert: [sdsb-security-officer]
-   import_sign_cert: [sdsb-security-officer, sdsb-registration-officer]
-   activate_disable_auth_cert: [sdsb-security-officer]
-   activate_disable_sign_cert: [sdsb-security-officer, sdsb-registration-officer]
-   send_auth_cert_reg_req: [sdsb-security-officer]
-   send_auth_cert_del_req: [sdsb-security-officer]
-   delete_auth_cert: [sdsb-security-officer]
-   delete_sign_cert: [sdsb-security-officer, sdsb-registration-officer]
-   delete_auth_key: [sdsb-security-officer]
-   delete_sign_key: [sdsb-security-officer, sdsb-registration-officer]
- view_sys_params: [sdsb-security-officer, sdsb-system-administrator]
-   view_distributors: [sdsb-system-administrator, sdsb-security-officer]
-     add_distributor: [sdsb-security-officer]
-     delete_distributor: [sdsb-security-officer]
-   view_tsps: [sdsb-security-officer, sdsb-system-administrator]
-     add_tsp: [sdsb-security-officer]
-     delete_tsp: [sdsb-security-officer]
-   view_async_params: [sdsb-security-officer, sdsb-system-administrator]
-     edit_async_params: [sdsb-system-administrator]
-   view_internal_ssl_cert: [sdsb-security-officer, sdsb-system-administrator]
-     export_internal_ssl_cert: [sdsb-security-officer, sdsb-system-administrator]
-     generate_internal_ssl: [sdsb-security-officer, sdsb-system-administrator]
- backup_configuration: [sdsb-system-administrator]
- restore_configuration: [sdsb-system-administrator]
