# This file contains the full list of privileges used in UI authorization.
# Each privilege is mapped to a list of roles that it belongs to.

# roles:
#   - sdsb-security-officer
#   - sdsb-registration-officer
#   - sdsb-service-administrator
#   - sdsb-system-administrator
#   - sdsb-system-auditor
#   - sdsb-users-administrator

- init_config: [sdsb-system-administrator]
- view_clients: [sdsb-security-officer, sdsb-registration-officer, sdsb-service-administrator]
-   add_client: [sdsb-registration-officer]
-   send_client_reg_req: [sdsb-registration-officer]
-   view_client_details: [sdsb-registration-officer, sdsb-service-administrator]
-     send_client_del_req: [sdsb-registration-officer]
-     delete_client: [sdsb-registration-officer]
-     view_client_groups: [sdsb-registration-officer, sdsb-service-administrator]
-     view_client_services: [sdsb-service-administrator]
-       add_wsdl: [sdsb-service-administrator]
-       enable_disable_wsdl: [sdsb-service-administrator]
-       refresh_wsdl: [sdsb-service-administrator]
-       delete_wsdl_missing_services: [sdsb-service-administrator]
-       delete_wsdl: [sdsb-service-administrator]
-       mark_wsdl_publishable: [sdsb-service-administrator]
-       publish_wsdls: [sdsb-service-administrator]
-       edit_service_params: [sdsb-service-administrator]
-       view_service_acl: [sdsb-service-administrator]
-       edit_service_acl: [sdsb-service-administrator]
-       import_export_service_acl: [sdsb-service-administrator]
-       export_client_services_acl: [sdsb-service-administrator]
-     view_internal_servers: [sdsb-service-administrator, sdsd-security-officer]
-     view_internal_certificates: [sdsb-service-administrator, sdsd-security-officer]
-     view_internal_certficate: [sdsb-service-administrator, sdsd-security-officer]
-     add_internal_certificate: [sdsb-service-administrator, sdsd-security-officer]
-     delete_internal_certificate: [sdsb-service-administrator, sdsd-security-officer]
-     view_ssl_certificate: [sdsb-service-administrator, sdsd-security-officer]
-     export_ssl_certificate: [sdsb-service-administrator, sdsd-security-officer]
-     view_connection_type: [sdsb-service-administrator, sdsd-security-officer]
-     edit_connection_type: [sdsb-service-administrator, sdsd-security-officer]
- view_subjects: [sdsb-service-administrator]
-   view_subject_open_services: [sdsb-service-administrator]
-     edit_subject_open_services: [sdsb-service-administrator]
-     import_export_subject_acl: [sdsb-service-administrator]
- view_async_reqs: [sdsb-system-administrator]
-   view_async_req_last_send_result: [sdsb-system-administrator]
-   reset_async_req_send_count: [sdsb-system-administrator]
#   refresh_async_reqs: [sdsb-system-administrator] # same as view_async_reqs
-   remove_restore_async_req: [sdsb-system-administrator]
- view_async_reqs_log: [sdsb-system-administrator]
- view_keys: [sdsb-security-officer, sdsb-registration-officer, sdsb-system-administrator]
-   login_logout_tokens: [sdsb-security-officer, sdsb-system-administrator]
-   generate_key: [sdsb-security-officer, sdsb-registration-officer]
-   generate_auth_cert_req: [sdsb-security-officer]
-   generate_sign_cert_req: [sdsb-security-officer, sdsb-registration-officer]
# TODO: UI does not know which one is being uploaded, should inspect?
-   import_auth_cert: [sdsb-security-officer]
-   import_sign_cert: [sdsb-security-officer, sdsb-registration-officer]
-   activate_disable_auth_cert: [sdsb-security-officer]
-   activate_disable_sign_cert: [sdsb-security-officer, sdsb-registration-officer]
-   send_auth_cert_reg_req: [sdsb-security-officer]
-   send_auth_cert_del_req: [sdsb-security-officer]
-   delete_auth_cert: [sdsb-security-officer]
-   delete_sign_cert: [sdsb-security-officer, sdsb-registration-officer]
- view_sys_params: [sdsb-security-officer, sdsb-system-administrator]
-   get_global_distributors: [sdsb-system-administrator, sdsb-security-officer]
-       add_global_distributor: [sdsb-security-officer]
-       delete_global_distributor: [sdsb-security-officer]
-   get_tsps: [sdsb-security-officer, sdsb-system-administrator]
-       add_tsp: [sdsb-security-officer]
-       edit_tsp: [sdsb-security-officer]
-       delete_tsp: [sdsb-security-officer]
-   get_async_requests: [sdsb-security-officer, sdsb-system-administrator]
-       edit_async_requests: [sdsb-system-administrator]
-   get_ssl: [sdsb-security-officer, sdsb-system-administrator]
-       gen_ssl: [sdsb-system-administrator]
-       export_ssl: [sdsb-system-administrator]
- backup_configuration: [sdsb-system-administrator]
- restore_configuration: [sdsb-system-administrator]
