# This file contains the full list of privileges used in UI authorization.
# Each privilege is mapped to a list of roles that it belongs to.

# roles:
#   - xroad-security-officer
#   - xroad-registration-officer
#   - xroad-service-administrator
#   - xroad-system-administrator

- init_config: [xroad-system-administrator]
- view_clients: [xroad-security-officer, xroad-registration-officer, xroad-service-administrator]
-   add_client: [xroad-registration-officer]
-   send_client_reg_req: [xroad-registration-officer]
-   view_client_details: [xroad-registration-officer, xroad-service-administrator]
-     send_client_del_req: [xroad-registration-officer]
-     delete_client: [xroad-registration-officer]
-   view_client_local_groups: [xroad-service-administrator]
-     add_local_group: [xroad-service-administrator]
-     edit_local_group_desc: [xroad-service-administrator]
-     edit_local_group_members: [xroad-service-administrator]
-     delete_local_group: [xroad-service-administrator]
-   view_client_services: [xroad-service-administrator]
-     add_wsdl: [xroad-service-administrator]
-     enable_disable_wsdl: [xroad-service-administrator]
-     refresh_wsdl: [xroad-service-administrator]
-     delete_wsdl_missing_services: [xroad-service-administrator]
-     delete_wsdl: [xroad-service-administrator]
-     edit_service_params: [xroad-service-administrator]
-     view_service_acl: [xroad-service-administrator]
-     edit_service_acl: [xroad-service-administrator]
-     import_export_service_acl: [xroad-service-administrator]
-     export_client_services_acl: [xroad-service-administrator]
-   view_client_acl_subjects: [xroad-service-administrator]
-     view_acl_subject_open_services: [xroad-service-administrator]
-       edit_acl_subject_open_services: [xroad-service-administrator]
-   view_client_internal_certs: [xroad-service-administrator, xroad-registration-officer]
-     view_client_internal_cert_details: [xroad-service-administrator, xroad-registration-officer]
-     add_client_internal_cert: [xroad-service-administrator, xroad-registration-officer]
-     delete_client_internal_cert: [xroad-service-administrator, xroad-registration-officer]
-     view_client_internal_connection_type: [xroad-service-administrator, xroad-registration-officer]
-     edit_client_internal_connection_type: [xroad-service-administrator, xroad-registration-officer]
-     view_proxy_internal_cert: [xroad-service-administrator, xroad-registration-officer]
-     export_proxy_internal_cert: [xroad-service-administrator, xroad-registration-officer]
- view_async_reqs: []
-   view_async_req_last_send_result: []
-   reset_async_req_send_count: []
-   remove_restore_async_req: []
- view_async_reqs_log: []
- view_keys: [xroad-security-officer, xroad-registration-officer, xroad-system-administrator]
-   activate_token: [xroad-security-officer, xroad-system-administrator]
-   deactivate_token: [xroad-security-officer, xroad-system-administrator]
-   generate_key: [xroad-security-officer, xroad-registration-officer]
-   delete_key: [xroad-security-officer, xroad-registration-officer]
-   generate_auth_cert_req: [xroad-security-officer]
-   generate_sign_cert_req: [xroad-security-officer, xroad-registration-officer]
-   generate_internal_cert_req: [xroad-security-officer]
-   import_auth_cert: [xroad-security-officer]
-   import_sign_cert: [xroad-security-officer, xroad-registration-officer]
-   activate_disable_auth_cert: [xroad-security-officer]
-   activate_disable_sign_cert: [xroad-security-officer, xroad-registration-officer]
-   send_auth_cert_reg_req: [xroad-security-officer]
-   send_auth_cert_del_req: [xroad-security-officer]
-   delete_auth_cert: [xroad-security-officer]
-   delete_sign_cert: [xroad-security-officer, xroad-registration-officer]
-   delete_auth_key: [xroad-security-officer]
-   delete_sign_key: [xroad-security-officer, xroad-registration-officer]
- view_sys_params: [xroad-security-officer, xroad-system-administrator]
-   view_anchor: [xroad-security-officer, xroad-system-administrator]
-     download_anchor: [xroad-security-officer, xroad-system-administrator]
-     upload_anchor: [xroad-security-officer]
-   view_tsps: [xroad-security-officer, xroad-system-administrator]
-     add_tsp: [xroad-security-officer]
-     delete_tsp: [xroad-security-officer]
-   view_async_params: []
-     edit_async_params: []
-   view_internal_ssl_cert: [xroad-security-officer, xroad-system-administrator]
-     export_internal_ssl_cert: [xroad-security-officer, xroad-system-administrator]
-     generate_internal_ssl: [xroad-security-officer, xroad-system-administrator]
- backup_configuration: [xroad-system-administrator]
- diagnostics: [xroad-system-administrator]
- restore_configuration: [xroad-system-administrator]
