---
ss_modules:
  monitor:
    dir: monitor
    build: build
    lib: monitor-1.0.jar
    target: /usr/share/xroad/jlib
  proxy:
    dir: proxy
    build: build
    lib: proxy-1.0.jar
    target: /usr/share/xroad/jlib
  addon-proxy:
    dir: addons/proxymonitor/metaservice
    build: build
    lib: proxymonitor-metaservice-1.0.jar
    target: /usr/share/xroad/jlib/addon/proxy
  configuration-client:
    dir: configuration-client  
    build: build
    lib: configuration-client-1.0.jar
    target: /usr/share/xroad/jlib
  proxy-ui:
    dir: proxy-ui  
    build: warble
    lib: proxy-ui.war
    target: /usr/share/xroad/jlib/webapps
