---
# This playbook initializes X-Road environment


- hosts: lxd-servers
  roles:
    - role: init-lxd

- hosts: ss-servers, cs-servers, cp-servers
  become: yes
  become_user: root
  gather_facts: no
  pre_tasks:
    - name: 'Install python2'
      raw: apt-get -y install python
    
- hosts: cs-servers
  become: yes
  become_user: root
  roles:
    - palveluvayla-cs

- hosts: cp-servers
  become: yes
  become_user: root
  roles:
    - palveluvayla-cp

- hosts: ss-servers, cs-servers, cp-servers
  become: yes
  become_user: root
  gather_facts: no
  pre_tasks:
    - raw: apt-get -y install python

- hosts: ss-servers
  become: yes
  become_user: root
  roles:
    - palveluvayla-ss
    
- hosts: ca-servers
  become: yes
  become_user: root
  roles:
    - role: palveluvayla-ca
      tags: [ 'ca' ]
